all: zad1_reader zad1_writer zad2
zad1_reader: zad1_reader.c
	gcc -o zad1_reader zad1_reader.c -Wall -ansi
zad1_writer: zad1_writer.c
	gcc -o zad1_writer zad1_writer.c -Wall -ansi
zad2: zad2.c
	gcc -o zad2 zad2.c -Wall -ansi
